### ISSUE TITLE
Error: Cannot find module "sqlite-websql-orm/public_api"

### ISSUE THREAD

**Issue by MatthieuFereyre** [blixit/sqlite-websql-orm#2] opened 2018-09-07 15:11 UTC
Hello,

I try to use sqlite-websql-orm in an ionic app.
I use the version 1.1.2 and I have the error :
Error: Cannot find module "sqlite-websql-orm/public_api"
when starting the app.

Could you help me ?
Thank you

**Comment by blixit** [comment] 2018-09-24 20:29
Hi could you give more informations about your environment to help me to reproduce this error ?
- ionic version
- node version
- commands you typed

**Comment by MatthieuFereyre** [comment] 2018-09-25 07:18
Hi,

Ionic : 4.12.2
Node : 10.9.4

The comand is just an import :
import { AbstractEntity, Column } from "sqlite-websql-orm/public_api";

It does not compile this code, by throwing the error I gave you before.

**Comment by blixit** [comment] 2018-09-25 07:48
ok thanks. I'm currently at work. This night I will take a look.

**Comment by blixit** [comment] 2018-09-25 15:39
I forgot to ask @angular/cli version

**Comment by MatthieuFereyre** [comment] 2018-09-25 15:50
6.1.7

**Comment by MatthieuFereyre** [comment] 2018-09-25 15:51
I give you my dependencies :

  "dependencies": {
    "@angular/animations": "^6.1.7",
    "@angular/common": "^6.1.7",
    "@angular/compiler": "^6.1.7",
    "@angular/compiler-cli": "^6.1.7",
    "@angular/core": "^6.1.7",
    "@angular/forms": "^6.1.7",
    "@angular/http": "^6.1.7",
    "@angular/platform-browser": "^6.1.7",
    "@angular/platform-browser-dynamic": "^6.1.7",
    "@ionic-native/camera": "^4.12.2",
    "@ionic-native/core": "^4.12.2",
    "@ionic-native/geolocation": "^4.14.0",
    "@ionic-native/splash-screen": "^4.12.2",
    "@ionic-native/sqlite": "^4.12.2",
    "@ionic-native/status-bar": "^4.12.2",
    "cordova-android": "^7.1.1",
    "cordova-ios": "^4.5.5",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^2.1.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.4.0",
    "ionic-angular": "^3.9.2",
    "ionicons": "^3.0.0",
    "leaflet": "^1.3.4",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.2",
    "sw-toolbox": "^3.6.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@ionic-native/device": "^4.12.2",
    "@ionic/app-scripts": "^3.2.0",
    "@ngx-translate/core": "~10.0.2",
    "@ngx-translate/http-loader": "~3.0.1",
    "@types/jest": "^23.3.1",
    "@types/node": "^10.9.4",
    "babel-core": "^6.26.3",
    "babel-jest": "^23.4.2",
    "ionic-mocks": "^1.3.0",
    "jest": "^23.5.0",
    "jest-jenkins-reporter": "^1.0.2",
    "moment": "^2.22.1",
    "reflect-metadata": "^0.1.12",
    "supertest": "^3.1.0",
    "ts-jest": "^23.1.4",
    "typescript": "^2.6.2"
  },

**Comment by MatthieuFereyre** [comment] 2018-09-25 15:53
sqlite-websql-orm  is not in the list (i removed it since i could not
compile)

**Comment by blixit** [comment] 2018-09-26 07:21
yesterday I found the issue, it's related to Angular and node environments. I hope i will fix the issue by this end of day or later before the end of week. Sorry for the delay

**Comment by MatthieuFereyre** [comment] 2018-09-26 10:56
Thank you. I'll try it next week.

**Comment by blixit** [comment] 2018-09-30 21:43
Hi @MatthieuFereyre 
As I said, the issue was related to my project environment but for now I'm not able to fix it. Ngc doesnt give explicit errors.

I know it's not a good practice but I just created a temporary package here ( https://www.npmjs.com/package/swo-lib ) that will be deleted once the issue resolved. The only difference is the package name.
Tell me if you are able to compile with it.

An exemple:
```ts
// temporary package - will be removed once the issue solved
import { SqliteWebsqlOrmModule, ADAPTERS, SchemaFactory } from 'swo-lib'; 

// original package  -  fix in progress
// import { SqliteWebsqlOrmModule, ADAPTERS, SchemaFactory } from 'sqlite-websql-orm';
```

**Comment by blixit** [comment] 2018-09-30 23:01
Re-hi @MatthieuFereyre,
I think the problem is solved with the version 1.2.1. Now you should be able to do: 
```ts
import { SqliteWebsqlOrmModule, ADAPTERS, SchemaFactory } from 'sqlite-websql-orm';
```

:warning: don't forget to install both: `npm i @ionic-native/core --save` and `npm i @ionic-native/sqlite --save` to avoid getting following errors when serving the app:

```bash
ERROR in ../node_modules/@ionic-native/core/plugin.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '/var/www/html/node_modules/@ionic-native/core'
```

Please tell me, if the issue is solved on your side too.

**Comment by blixit** [comment] 2018-10-03 22:06
hi @MatthieuFereyre , without any answer from you I will close this issue this weekend.

**Comment by MatthieuFereyre** [comment] 2018-10-04 07:07
Yes you can close it, I'm afraid I cannot test it until some weeks.

**Comment by blixit** [comment] 2018-10-04 10:07
ok. don't hesitate to reopen the issue if needed.

**Closed as completed by blixit** 2018-10-04 10:07 UTC

**Comment by MatthieuFereyre** [comment] 2018-10-05 13:07
I rapidly tested it and it seems to work.
A big thank you.

**Comment by blixit** [comment] 2018-10-05 18:15
great !! If you think you can contribute you are welcome
